"""add public_id to files

Revision ID: 0c88c54d4b1b
Revises: 2072fdaeb10b
Create Date: 2025-12-25 06:05:57.159032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c88c54d4b1b'
down_revision = '2072fdaeb10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
