"""add private_chat_id to files

Revision ID: 4b774f4d2ec7
Revises: 0c88c54d4b1b
Create Date: 2025-12-25 06:24:19.901193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b774f4d2ec7'
down_revision = '0c88c54d4b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_chat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'private_chats', ['private_chat_id'], ['id'])
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('private_chat_id')

    # ### end Alembic commands ###
