"""Add private_message_id to files table

Revision ID: add_private_message_id
Revises: e0beca32b9d5
Create Date: 2026-01-04 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_private_message_id'
down_revision = 'e0beca32b9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('private_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'private_messages', ['private_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'private_message_id')
    # ### end Alembic commands ###
