"""add unread count model

Revision ID: e0beca32b9d5
Revises: 4b774f4d2ec7
Create Date: 2026-01-02 22:04:02.156770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0beca32b9d5'
down_revision = '4b774f4d2ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unread_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['private_chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='unique_user_chat')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('files_private_message_id_fkey'), type_='foreignkey')
        batch_op.drop_column('private_message_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('files_private_message_id_fkey'), 'private_messages', ['private_message_id'], ['id'])

    op.drop_table('unread_counts')
    # ### end Alembic commands ###
